fastlane_version '2.217.0'

desc 'test lane'
lane :test do
  print "TEST SUCCESSFUL!"
end

platform :ios do

 desc 'Fetch certificates and provisioning profiles'
 lane :certificates do
 end

 desc 'Build the iOS application.'
 lane :build do
  sh("ns", "prepare", "ios", "--release", "--clean", "--env.production")

    match(type: "appstore")

    gym(
      scheme: "nsvue3template",
      project: './platforms/ios/nsvue3template.xcodeproj',
      # workspace: './platforms/ios/nsvue3template.xcworkspace',
      export_method: "app-store"
    )
 end

 desc 'Ship to Testflight.'
 lane :beta do
    build

    changelog_from_git_commits

    upload_to_testflight(
      beta_app_feedback_email: "<Y0UR_EMAIL>",
      beta_app_description: "Simple template Vue 3 for Nativescript",
      demo_account_required: false,
      distribute_external: true,
      groups: ["beta testers"],
      notify_external_testers: true,
      beta_app_review_info: {
        contact_email: "<YOUR_EMAIL>",
        contact_first_name: "<YOUR_NAME>",
        contact_last_name: "<YOUR_LAST_NAME>",
        contact_phone: "<YOUR_PHONE>",
        demo_account_name: "",
        demo_account_password: "",
        notes: "<3 Thank you for reviewing!"
      },
    )
end

end

platform :android do

 desc 'Build the Android application.'
 lane :build do
   sh("ns", "build", "android", "--release", "--clean", "--env.production",
        "--key-store-path", "../keystore/keystore.jks",
        "--key-store-password", ENV["KEYSTORE_PASSWORD"],
        "--key-store-alias", ENV["KEYSTORE_ALIAS"],
        "--key-store-alias-password", ENV["KEYSTORE_ALIAS_PASSWORD"]
      )
 end

 desc 'Ship to Playstore Alpha track.'
 lane :alpha do
  build

    changelog_from_git_commits

    supply(
      package_name: '<PACKAGE_NAME>',
      track: 'alpha',
      track_promote_to: 'alpha',
      json_key_data: ENV["PLAYSTORE_JSON_KEY_DATA"],
      apk: './platforms/android/app/build/outputs/apk/release/app-release.apk'
    )
 end

 desc 'Ship to Playstore Beta track.'
 lane :beta do
  build

    changelog_from_git_commits

    supply(
      package_name: '<PACKAGE_NAME>',
      track: 'beta',
      track_promote_to: 'beta',
      json_key_data: ENV["PLAYSTORE_JSON_KEY_DATA"],
      apk: './platforms/android/app/build/outputs/apk/release/app-release.apk'
    )
 end

 desc 'Ship to Playstore Production track.'
 lane :prod do
  build

    changelog_from_git_commits

    supply(
      package_name: '<PACKAGE_NAME>',
      track: 'production',
      track_promote_to: 'production',
      json_key_data: ENV["PLAYSTORE_JSON_KEY_DATA"],
      aab: './platforms/android/app/build/outputs/bundle/release/app-release.aab'
    )
 end

end